### ISSUE TITLE
Permission denied(publickey)

### ISSUE THREAD

**Issue by saloumfall** [radibit/js-tips-slack-bot#1]
Hi!
I got this message when i try to clone this repo: "Permission denied (publickey). fatal: could not read from remote repository".

Thanks for  your answer

**Comment by radibit** [comment]
Hey @saloumfall 

The problem you hit is due to the fact that you need to add your public SSH key to GitHub in order to clone through SSH. 

The reason why is because git needs to authenticate through SSH to GitHub's servers in order to do the clone. And in order to do that, they need to have your public key.

If you haven't generated any SSH keys so far, you can follow the steps listed in the following [GitHub helper doc](https://help.github.com/articles/generating-an-ssh-key/).

Alternatively you can clone the repo using https with the following command:

```
git clone https://github.com/radibit/js-tips-slack-bot.git
```

**Comment by saloumfall** [comment]
Hi thanks for tour response !


FALL Saloum - Front-End Web Developer
34, quai de la Loire - 75019 Paris - France

relaxnews.com, facebook, twitter, NYSE Alternext : ALRLX

**Comment by radibit** [comment]
ok, I'm closing this issue :)
