### ISSUE TITLE
The bot never start sending the message

### ISSUE THREAD

**Issue by lukyth** [radibit/js-tips-slack-bot#3]
Hey @radibit !

Right now I'm testing on my local machine and I can't send any message to Slack. Everything is fine, I can get the data from GitHub. It just won't send to Slack.

I found out that the reason is the `open` event is fired when [websocket connection is open and ready to communicate](https://github.com/mishk0/slack-bot-api#events) (which is when a bot is successfully created). And a `postMessageToGroup` is bind to the open event.

```
bot.on( 'open', function() {
  ...
  bot.postMessageToGroup( process.env.SLACK_GROUP, jsTipMessage, params );
} );
```

which is inside `ghget` callback.

So, when a bot is successfully created, `open` event is fired, there's still nothing binding to that event. (There's still no response from GitHub so a callback still not fired). And the `open` event is never fired again because the bot is only created once.

I'm pretty sure it works just fine last night, but I don't really know why. (Maybe because Slackbot was created slower than GitHub response, I'm trying this on another network from last night.) So I'm wondering if you got the same problem as mine.

**Comment by radibit** [comment]
Hi @lukyth 

The problem you hit I believe is due to the difference between sending message to a public channel ( `postMessageToChannel` ) or a private group ( `postMessageToGroup` ). 

In the second case the Slack bearer token you're creating should be associated to a user who is a member of this group. This is not a requirement for the public channels. More info can be found here https://api.slack.com/methods/chat.postMessage

My idea behind this slack bot was to make it work with private groups where it can post automatically the latest jstips. However I can see the limitation of that so I will expose this to the `.env` configuration, so it can be changed.

Hope this makes sense to you :-)

**Comment by radibit** [comment]
@lukyth I just updated the `.env` config variables and tested successfully the cases of sending tips to a private group or a public channel.

Can you please try and confirm?

**Comment by lukyth** [comment]
@radibit I tested your latest commit and it works on Heroku but not on my local machine (I can only test with sending tips to public channel). Did you test on both Heroku and your local machine? I don't really know why it behave like this.

And one other thing, right now I got many same tips occasionally from the one I deployed to Heroku. Is it because I'm using Heroku's free plan and my dyno got restarted from time to time?

Anyway, thank you for helping me this much. I really appreciate that. :)

**Comment by radibit** [comment]
@lukyth Yep, I tested locally and on Heroku, the both ways were working fine for me. Please check again the new env config properties, though if your deployed version works ok, there shouldn't be a problem with the local one. 

Regarding the repetition on the tips, Heroku is restarting the worker every day for 6 hours as this is part of the free plan. However that won't be an issue if there is a new tip every day. As you might noticed there weren't any new posts the last three days and that's why the bot is still sending the last tip from 17.02. The reason for that is because the people behind the JS Tips initiative are thinking of changes for  the tips review process and how often new tips will be published. Once they applied the new ideas I will adapt the slack bot accordingly.

Feel free to update the status of this issue :)

**Comment by lukyth** [comment]
Thanks! Closing this issue for now. Looking forward to an adaptation for the new JS Tips!
